---
version: '3.6'

services:
  project-name-raw:
    container_name: '${PROJECT_NAME_UPPER_NAME}'
    image: ${PROJECT_NAME_UPPER_IMG}:${PROJECT_NAME_UPPER_VERSION_PROD}
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:80"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 10s
    environment:
    - 'API_URL=${PROJECT_NAME_UPPER_API_URL_PROD}'
    - 'APP_HOST=${PROJECT_NAME_UPPER_APP_HOST_PROD}'
    - 'OIDC_DOMAIN=${PROJECT_NAME_UPPER_OIDC_DOMAIN_PROD}'
    - 'OIDC_CLIENT_ID=${PROJECT_NAME_UPPER_OIDC_CLIENT_ID_PROD}'
    ports:
    - ${PROJECT_NAME_UPPER_PORT}:80
    restart: unless-stopped
